### ISSUE TITLE
Adicionar título na página index

### ISSUE THREAD

**Issue by adriano-lopes-ba** [adriano-team/prj-remoto#1]
Adicionar título na página index para melhorar  a identificação da página pelo navegador.

**Comment by adriano-lopes-ba** [comment]
Adriano, por favor, verificar este problema.

**Comment by adriano-sampaio** [comment]
Alteração realizada via push direto na branch master.

**Comment by adriano-lopes-ba** [comment]
Fechada via PR #2 de adriano-sampaio.
